sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 4l9hn9YNXUG+hdnGOyozgvkRO6UjX/thbx9D80WZFj7OqV/x+X+/upLgi7tVEU70ZQWYrPWwZ/D0mgm+QrghnvNwUA91ClPxxh3N2IfxMpm0prwaoM9R/mpG12YW4sEZs0fSH7VcQs5pdkxlxHvWluV2a1xKtewcd57DvC035PVKahoBIuoWnTKaGEwn3ngQTIWgVg6WhLO8uXXiIBDZRieefekI9NBOsDyXGONbPsn5NmYUFsGpwf8ZhsMdCCuooBg7rMVX0lUYD2SYq6Q0bNyzg2GGJpCYn3UBm2i6bc3vpdjoBaauNjKEvWeH3Fw5lPG3cwP71OeWSSoAVelWIupJuMR+rgmgx4RpQtX/eal2l8F67sz05CnBDzpWHzPkGfca6ITnwVl6PS30IM0va9kZeSY/rrg901NV00ysFRrlYhLfLq+PQDZaZBlRIgsyF8yNcPpFEqVocLF6TppE8Pj15+0gDM1aPMIg4Kj+vP28h5PB0dORkMCuiTFo2vQXnnFhQYJES8mQcGR3WLCn9zBs2jqaXB67+haJmJR+gwvUdu91DOyhhrzFYq62+jjxBW9Mu/EKVbnA8yC4kCkbN08qVijg7dh3qn69ii8ociKxH7NkdDd4ZFBqeFC/ahDM52S4q/VqT16xeFqSUwnoZfqCrfWmnC6kVJx/W8NrzNE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/When-Valmond-Came-to-Pontiac-The-Story-of-a-Lost-Napoleon-Volume-3_6204
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy